export const PREVIEW_3D_MAX_GRID_WIDTH_RATIO = 0.84;
export const PREVIEW_3D_HORIZON_VIEWPORT_MULTIPLIER = 0.6;
export const PREVIEW_3D_NEAR_SPEED_MULTIPLIER = 2.05;
export const PREVIEW_3D_FAR_DISTANCE_MULTIPLIER = 2.2;
export const PREVIEW_3D_CONNECTOR_CLIP_PADDING = 80;
export const PREVIEW_3D_CONNECTOR_MAX_SEGMENT_HEIGHT = 18;
export const PREVIEW_3D_CAMERA_BASE_Z = -7;
export const PREVIEW_3D_CAMERA_Z_PER_HEIGHT = -14;
export const PREVIEW_3D_CAMERA_Y_OFFSET_PER_HEIGHT = -120;
export const PREVIEW_3D_CAMERA_EASE_PER_SECOND = 20;

export const DR3FP_PREVIEW_RECEIVER_ORIGIN = 'http://127.0.0.1:27373';
export const DR3FP_PREVIEW_RECEIVER_TIMEOUT_MS = 30_000;
export const DR3FP_PREVIEW_RECEIVER_POLL_MS = 250;
