export const PREVIEW_NOTE_TEXTURE_URLS: Record<number, string> = {
  1: new URL('../assets/preview-note-sprites/note1.png', import.meta.url).href,
  2: new URL('../assets/preview-note-sprites/note2.png', import.meta.url).href,
  3: new URL('../assets/preview-note-sprites/note3.png', import.meta.url).href,
  4: new URL('../assets/preview-note-sprites/note4.png', import.meta.url).href,
  5: new URL('../assets/preview-note-sprites/note5.png', import.meta.url).href,
  6: new URL('../assets/preview-note-sprites/note6.png', import.meta.url).href,
  7: new URL('../assets/preview-note-sprites/note7.png', import.meta.url).href,
  8: new URL('../assets/preview-note-sprites/note8.png', import.meta.url).href,
  9: new URL('../assets/preview-note-sprites/note9.png', import.meta.url).href,
  10: new URL('../assets/preview-note-sprites/note10.png', import.meta.url).href,
  11: new URL('../assets/preview-note-sprites/note11.png', import.meta.url).href,
  12: new URL('../assets/preview-note-sprites/note12.png', import.meta.url).href,
  13: new URL('../assets/preview-note-sprites/note13.png', import.meta.url).href,
  14: new URL('../assets/preview-note-sprites/note14.png', import.meta.url).href,
  15: new URL('../assets/preview-note-sprites/note15.png', import.meta.url).href,
  16: new URL('../assets/preview-note-sprites/note16.png', import.meta.url).href,
  17: new URL('../assets/preview-note-sprites/note17.png', import.meta.url).href,
  18: new URL('../assets/preview-note-sprites/note18.png', import.meta.url).href,
  19: new URL('../assets/preview-note-sprites/note19.png', import.meta.url).href,
  20: new URL('../assets/preview-note-sprites/note20.png', import.meta.url).href,
  21: new URL('../assets/preview-note-sprites/note21.png', import.meta.url).href,
  22: new URL('../assets/preview-note-sprites/note22.png', import.meta.url).href,
  23: new URL('../assets/preview-note-sprites/note23.png', import.meta.url).href,
  24: new URL('../assets/preview-note-sprites/note24.png', import.meta.url).href,
  25: new URL('../assets/preview-note-sprites/note25.png', import.meta.url).href,
  26: new URL('../assets/preview-note-sprites/note26.png', import.meta.url).href,
  27: new URL('../assets/preview-note-sprites/note27.png', import.meta.url).href,
};

export const PREVIEW_NOTE_ARROW_URLS: Record<number, string> = {
  1: new URL('../assets/preview-note-sprites/arrow1.png', import.meta.url).href,
  2: new URL('../assets/preview-note-sprites/arrow2.png', import.meta.url).href,
  9: new URL('../assets/preview-note-sprites/arrow9.png', import.meta.url).href,
  13: new URL('../assets/preview-note-sprites/arrow13.png', import.meta.url).href,
  14: new URL('../assets/preview-note-sprites/arrow14.png', import.meta.url).href,
  15: new URL('../assets/preview-note-sprites/arrow15.png', import.meta.url).href,
  16: new URL('../assets/preview-note-sprites/arrow16.png', import.meta.url).href,
  25: new URL('../assets/preview-note-sprites/arrow25.png', import.meta.url).href,
  26: new URL('../assets/preview-note-sprites/arrow26.png', import.meta.url).href,
  27: new URL('../assets/preview-note-sprites/arrow27.png', import.meta.url).href,
};

export const PREVIEW_HOLD_TEXTURE_URLS: Record<number, string> = {
  4: new URL('../assets/preview-note-sprites/hold4.png', import.meta.url).href,
  6: new URL('../assets/preview-note-sprites/hold7.png', import.meta.url).href,
  7: new URL('../assets/preview-note-sprites/hold7.png', import.meta.url).href,
  11: new URL('../assets/preview-note-sprites/hold4.png', import.meta.url).href,
  17: new URL('../assets/preview-note-sprites/hold18.png', import.meta.url).href,
  18: new URL('../assets/preview-note-sprites/hold18.png', import.meta.url).href,
  19: new URL('../assets/preview-note-sprites/hold20.png', import.meta.url).href,
  20: new URL('../assets/preview-note-sprites/hold20.png', import.meta.url).href,
  21: new URL('../assets/preview-note-sprites/hold22.png', import.meta.url).href,
  22: new URL('../assets/preview-note-sprites/hold22.png', import.meta.url).href,
  23: new URL('../assets/preview-note-sprites/hold24.png', import.meta.url).href,
  24: new URL('../assets/preview-note-sprites/hold24.png', import.meta.url).href,
};
